spring:
  datasource:
#    url: jdbc:h2:file:~/data/uniman
#    url: jdbc:h2:mem:uniman
#    username: sa
#    password: password
    url: jdbc:mysql://localhost:3306/fti_uniman?useSSL=false
    username: root
    password: Joan@2000

    open-in-view: false
  h2:
    console.enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect


key: Administratori123++/@
tokenValidity: 60*60