spring:
  datasource:
    url: jdbc:h2:file:~/data/uniman
#    url: jdbc:h2:mem:uniman
    username: sa
    password: password
    driverClassName: org.h2.Driver
    show-sql: true
    open-in-view: false
#    initialize: true
#    platform: h2
#    schema: schema.sql
  h2:
    console.enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect