spring:
  datasource:
#    url: jdbc:h2:file:~/data/uniman
#    url: jdbc:h2:mem:uniman
    url: jdbc:mysql://localhost:3306/fti_uniman?useSSL=false
    username: root
    password: Joan@2000
    show-sql: true
    open-in-view: false
  h2:
    console.enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect