spring:
  datasource:
    url: ${UNIMAN_DB_URL}
    username: ${UNIMAN_DB_USERNAME}
    password: ${UNIMAN_DB_PASSWORD}

#    url: jdbc:postgresql://ec2-52-48-159-67.eu-west-1.compute.amazonaws.com:5432/db4r7ukl4at7s7
#    username: wjcchrrjsgfakw
#    password: 6bbe4476b1175f2d9c79dcfe5ad4b631378c644418d86773cb068dd01991f5bf
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect


key: Administratori123++/@
tokenValidity: 60*60