spring:
  datasource:
    url: jdbc:h2:file:~/data/uniman
    username: sa
    password: password
    driverClassName: org.h2.Driver
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  h2:
    console.enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect