spring:
  datasource:
    url: jdbc:h2:file:~/data/uniman
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect